project_id = "xusensadnrsodukuzndm"

[functions.get-exchange-rate]
verify_jwt = false

[functions.create-offramp-request]
verify_jwt = false

[functions.create-onramp-request]
verify_jwt = false

[functions.get-payment-request]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.admin-auth-rate-limit]
verify_jwt = false

[functions.admin-dashboard]
verify_jwt = false

[functions.validate-admin-token]
verify_jwt = false

[functions.admin-audit-log]
verify_jwt = false

[functions.search-transactions]
verify_jwt = false

[functions.blockchain-monitor]
verify_jwt = false

[functions.blockchain-webhook]
verify_jwt = false

[functions.toggle-blockchain-visibility]
verify_jwt = false

[functions.toggle-country-visibility]
verify_jwt = false
