project_id = "xusensadnrsodukuzndm"

[functions.get-exchange-rate]
verify_jwt = false

[functions.create-offramp-request]
verify_jwt = false

[functions.create-onramp-request]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.admin-auth-rate-limit]
verify_jwt = false

[functions.admin-dashboard]
verify_jwt = false

[functions.validate-admin-token]
verify_jwt = false

[functions.admin-audit-log]
verify_jwt = false