// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-my-transactions.ts
import { createClient } from "npm:@supabase/supabase-js@^2.52.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_transactions_default = defineTool({
  name: "list_my_transactions",
  title: "List my transactions",
  description: "List the signed-in user's SikaPay transactions (both offramp and onramp), most recent first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max rows per type (default 20)."),
    type: z.enum(["all", "offramp", "onramp"]).optional().describe("Filter by transaction type. Defaults to 'all'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, type }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const cap = limit ?? 20;
    const kind = type ?? "all";
    const results = [];
    if (kind === "all" || kind === "offramp") {
      const { data, error } = await supabase.from("offramp_requests").select(
        "id, reference_id, status, amount, xof_amount, usd_amount, token, momo_number, momo_provider, exchange_rate, created_at"
      ).eq("user_id", userId).order("created_at", { ascending: false }).limit(cap);
      if (error) {
        return { content: [{ type: "text", text: error.message }], isError: true };
      }
      results.push(...(data ?? []).map((r) => ({ ...r, type: "offramp" })));
    }
    if (kind === "all" || kind === "onramp") {
      const { data, error } = await supabase.from("onramp_requests").select(
        "id, reference_id, status, crypto_amount, xof_amount, usd_amount, token, momo_number, momo_provider, recipient_address, exchange_rate, created_at"
      ).eq("user_id", userId).order("created_at", { ascending: false }).limit(cap);
      if (error) {
        return { content: [{ type: "text", text: error.message }], isError: true };
      }
      results.push(...(data ?? []).map((r) => ({ ...r, type: "onramp" })));
    }
    results.sort(
      (a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
    );
    return {
      content: [{ type: "text", text: JSON.stringify(results) }],
      structuredContent: { transactions: results }
    };
  }
});

// src/lib/mcp/tools/get-transaction.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.52.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_transaction_default = defineTool2({
  name: "get_transaction",
  title: "Get transaction",
  description: "Fetch one SikaPay transaction by its reference id (OFF-XXXXXX or ONR-XXXXXX). Only returns a row if it belongs to the signed-in user.",
  inputSchema: {
    reference_id: z2.string().trim().min(3).describe("Transaction reference id, e.g. OFF-A1B2C3 or ONR-X9Y8Z7.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ reference_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const userId = ctx.getUserId();
    const ref = reference_id.trim().toUpperCase();
    const table = ref.startsWith("ONR") ? "onramp_requests" : "offramp_requests";
    const { data, error } = await supabase.from(table).select("*").eq("reference_id", ref).eq("user_id", userId).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: `No transaction ${ref} found for this user.` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { transaction: { ...data, type: table === "onramp_requests" ? "onramp" : "offramp" } }
    };
  }
});

// src/lib/mcp/tools/create-onramp.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.52.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var create_onramp_default = defineTool3({
  name: "create_onramp_request",
  title: "Create onramp request",
  description: "Create a new onramp request (Mobile Money XOF -> stablecoin) on behalf of the signed-in user. Delegates to the create-onramp-request edge function, then tags the created row with the user's id.",
  inputSchema: {
    xofAmount: z3.number().min(100).max(6e5),
    token: z3.enum(["USDC", "USDT"]),
    network: z3.string().describe("Blockchain network, e.g. base, bsc, ethereum, polygon, solana."),
    recipientAddress: z3.string().min(1).max(64).describe("Destination wallet address."),
    momoNumber: z3.string().min(8).max(20),
    momoProvider: z3.string().optional(),
    countryId: z3.string().uuid().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    const res = await fetch(`${url}/functions/v1/create-onramp-request`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: key,
        Authorization: `Bearer ${key}`
      },
      body: JSON.stringify(input)
    });
    const body = await res.json();
    if (!res.ok || !body?.success) {
      return {
        content: [{ type: "text", text: body?.details || body?.error || "Failed to create onramp request" }],
        isError: true
      };
    }
    const service = createClient3(url, process.env.SUPABASE_SERVICE_ROLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    if (body.data?.id) {
      await service.from("onramp_requests").update({ user_id: ctx.getUserId() }).eq("id", body.data.id);
    }
    return {
      content: [{ type: "text", text: JSON.stringify(body.data) }],
      structuredContent: body.data
    };
  }
});

// src/lib/mcp/tools/create-offramp.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.52.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
var create_offramp_default = defineTool4({
  name: "create_offramp_request",
  title: "Create offramp request",
  description: "Create a new offramp request (stablecoin -> Mobile Money XOF) on behalf of the signed-in user. Delegates to the create-offramp-request edge function, then tags the created row with the user's id.",
  inputSchema: {
    amount: z4.number().positive().describe("Stablecoin amount the user will send."),
    token: z4.enum(["USDC", "USDT"]),
    network: z4.string().optional(),
    momoNumber: z4.string().min(8).max(20),
    momoProvider: z4.string().optional(),
    countryId: z4.string().uuid().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    const res = await fetch(`${url}/functions/v1/create-offramp-request`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: key,
        Authorization: `Bearer ${key}`
      },
      body: JSON.stringify(input)
    });
    const body = await res.json();
    if (!res.ok || !body?.success) {
      return {
        content: [{ type: "text", text: body?.details || body?.error || "Failed to create offramp request" }],
        isError: true
      };
    }
    const service = createClient4(url, process.env.SUPABASE_SERVICE_ROLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    if (body.data?.id) {
      await service.from("offramp_requests").update({ user_id: ctx.getUserId() }).eq("id", body.data.id);
    }
    return {
      content: [{ type: "text", text: JSON.stringify(body.data) }],
      structuredContent: body.data
    };
  }
});

// src/lib/mcp/tools/get-exchange-rate.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_exchange_rate_default = defineTool5({
  name: "get_exchange_rate",
  title: "Get exchange rate",
  description: "Get the current USD/XOF exchange rate used by SikaPay (includes the platform margin).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    const res = await fetch(`${url}/functions/v1/get-exchange-rate`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: key,
        Authorization: `Bearer ${key}`
      },
      body: "{}"
    });
    const body = await res.json();
    if (!res.ok || !body?.success) {
      return {
        content: [{ type: "text", text: body?.error ?? "Failed to fetch exchange rate" }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(body.data) }],
      structuredContent: body.data
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xusensadnrsodukuzndm";
var mcp_default = defineMcp({
  name: "sikapay-mcp",
  title: "SikaPay",
  version: "0.1.0",
  instructions: "Tools for SikaPay: convert stablecoins (USDC/USDT) to Mobile Money XOF (offramp) or Mobile Money to stablecoins (onramp). Use `get_exchange_rate` to fetch the current USD/XOF rate, `list_my_transactions` and `get_transaction` to read the signed-in user's transactions, and `create_onramp_request` / `create_offramp_request` to open a new transaction. All write tools act on behalf of the signed-in SikaPay user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_exchange_rate_default,
    list_my_transactions_default,
    get_transaction_default,
    create_onramp_default,
    create_offramp_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
